### ISSUE TITLE
Wrong price calculator for coins (airdrops) without market

### ISSUE THREAD

**Issue by firepol** [fatihacet/CoinTop#3]
I own 5 EOS on binance, and a few days ago I've read that binance distributed 1 EON for each owned EOS. Thus I got 5 EON. However, the price calculator shows the wrong price. 1 EON = 5 BTC is wrong. See screenshot.

I think the error is in exchange.js, in the calculatePrice function, but I have no time to investigate further...

![screen shot 2018-06-20 at 12 28 52](https://user-images.githubusercontent.com/1702718/41649971-9379fd2a-7485-11e8-97fd-9b2ac2bdec61.png)

For such cases I'd expect that the price is 0. Thus 5 EON = 0. As soon as they are listed in the exchange and they have a bid/ask value, then it can be used.

**Comment by fatihacet** [comment]
Sorry for the late reply. I am not maintaining this project anymore. Closing this issue.

> However, the price calculator shows the wrong price. 1 EON = 5 BTC is wrong. See screenshot.

I believe, you wish it to be true tho 😂
